/*
    I will try to implemnt the program in such way that it should not
    only multiplty square matrices but also matrices of different
    orders. In this program the user will enter the the dimensions
    for both metrices and data will be generated by random numbers for
    simplicity. We will distribute the first matrix amoung the threads.
*/

/*
    mat_mul_pthread <number of thread> <rows of matrix A> <columns of matrix A> <rows of matrix B> <culomns of matrix B>
    Program Command Arguments:
        1. Number of thread to execute the program on
        2. Number of rows of the first matrix
        3. Number of columns of the first matrix
        4. Number of rows of the second matrix
        5. Number of columns of the second matrix
*/

#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <time.h>

// number of rows and columns for each of the matrices
int row1, col1;
int row2, col2;

// global metrices to be multiplied
double *matrixA;
double *matrixB;
double *matrixC;

int thread_count;
pthread_t *thread_handle; // handle to store the number of threads

// this functions returns a random double between the given range
double get_random_number(double min, double max)
{
    // double between 0.0 and 1.0
    double number = (double)rand() / (double)RAND_MAX;
    // scaling the double between the given range
    return min + number * (max - min); // random double between min and max
}

// this function will be executed by each of the thread
void *mat_mul(void *args)
{
    long thread_id = (long)args;
    // printf("Hello from thread %ld\n", thread_id);

    int local_r1 = row1 / thread_count; // local rows for each of the thread
    int reminder = row1 % thread_count;

    int first_row = thread_id * local_r1;

    if (thread_id == thread_count - 1)
    {
        // if the rows are not completly divisible then the reamining rows
        // will be assigned to the last thread.
        local_r1 = local_r1 + reminder;
    }

    int last_row = first_row + local_r1;

    // perform the matrix multiplication into the global matrixC
    for (int i = first_row; i < last_row; i++)
    {
        for (int j = 0; j < col2; j++)
        {
            matrixC[i * col2 + j] = 0.0;
            for (int k = 0; k < col1; k++)
            {
                // multiply and populate the resultent matrix
                matrixC[i * col2 + j] += matrixA[i * col1 + k] * matrixB[k * col2 + j];
            }
        }
    }
}

int main(int argc, char *argv[])
{
    if (argc != 6)
    {
        printf("Enter all the arguments for the program\n");
        printf("Usage: %s <thread_count> <row1> <col1> <row2> <col2>\n", argv[0]);
        return 1;
    }

    // Seed for the random number generator
    srand(time(NULL));

    // initializing the values for the thread count and dimensions of the the matrices
    thread_count = atoi(argv[1]);
    row1 = atoi(argv[2]);
    col1 = atoi(argv[3]);
    row2 = atoi(argv[4]);
    col2 = atoi(argv[5]);

    if (col1 != row2)
    {
        printf("Dimension Error!!!!!!!\n");
        printf("Cannot multiply these two matrices\n");
        return 1;
    }

    // allocating memory to the thread handle
    thread_handle = malloc(thread_count * sizeof(pthread_t));

    // Allocating memory for the matrices
    matrixA = malloc(row1 * col1 * sizeof(double));
    matrixB = malloc(row2 * col2 * sizeof(double));
    matrixC = malloc(row1 * col2 * sizeof(double));

    // Populating the matrices with random numbers
    // first matrix
    for (int i = 0; i < row1; i++)
    {
        for (int j = 0; j < col1; j++)
        {
            matrixA[i * col1 + j] = get_random_number(0.0, 10.0);
        }
    }
    // second matrix
    for (int i = 0; i < row2; i++)
    {
        for (int j = 0; j < col2; j++)
        {
            matrixB[i * col2 + j] = get_random_number(0.0, 10.0);
        }
    }

    // below code was use to test the matrix data
    //  If the matrices are two large a=only top 5 x 5 submatrix will be shown
    int r, c;
    printf("First Matrix------\n");

    if (row1 > 5 || col1 > 5)
    {
        printf("(Only showing up to top 5x5 submatrix)\n");
    }
    r = (row1 > 5) ? 5 : row1;
    c = (col2 > 5) ? 5 : col1;

    for (int i = 0; i < r; i++)
    {
        for (int j = 0; j < c; j++)
        {
            printf("%lf\t", matrixA[i * col1 + j]);
        }
        printf("\n");
    }

    printf("\n\nSecond Matrix------\n");

    if (row2 > 5 || col2 > 5)
    {
        printf("(Only showing up to top 5x5 submatrix)\n");
    }
    r = (row2 > 5) ? 5 : row2;
    c = (col2 > 5) ? 5 : col2;

    for (int i = 0; i < r; i++)
    {
        for (int j = 0; j < c; j++)
        {
            printf("%lf\t", matrixB[i * col2 + j]);
        }
        printf("\n");
    }

    for (long thread = 0; thread < thread_count; thread++)
    {
        pthread_create(thread_handle, NULL, mat_mul, (void *)thread);
    }

    for (long thread = 0; thread < thread_count; thread++)
    {
        pthread_join(thread_handle[thread], NULL);
    }

    printf("\nFinal Matrix:\n");

    if (row1 > 5 || col2 > 5)
    {
        printf("(Only showing up to top 5x5 submatrix)\n");
    }

    r = (row1 > 5) ? 5 : row1;
    c = (col2 > 5) ? 5 : col2;

    for (int r = 0; r < row1; r++)
    {
        for (int c = 0; c < col2; c++)
        {
            printf("%lf\t", matrixC[r * col1 + c]);
        }
        printf("\n");
    }

    // Cleaning
    free(matrixA);
    free(matrixB);
    free(matrixC);
    free(thread_handle);

    return 0;
}