/*
    I will try to implemnt the program in such way that it should not
    only multiplty square matrices but also matrices of different
    orders. In this program the user will enter the the dimensions
    for both metrices and data will be generated by random numbers for
    simplicity.
*/

/*
    mat_mul_pthread <number of thread> <rows of matrix A> <columns of matrix A> <rows of matrix B> <culomns of matrix B>
    Program Command Arguments:
        1. Number of thread to execute the program on
        2. Number of rows of the first matrix
        3. Number of columns of the first matrix
        4. Number of rows of the second matrix
        5. Number of columns of the second matrix
*/

#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <time.h>

// number of rows and columns for each of the matrices
int row1, col1;
int row2, col2;

// global metrices to be multiplied
double *matrixA;
double *matrixB;
double *matrixC;

int thread_count;

// this functions returns a random double between the given range
double get_random_number(double min, double max)
{
    // double between 0.0 and 1.0
    double number  = (double)rand() / (double)RAND_MAX;
    // scaling the double between the given range
    return min + number * (max - min);       // random double between min and max
}



int main(int argc, char *argv[])
{
    if (argc != 6)
    {
        printf("Enter all the arguments for the program\n");
        printf("Usage: %s <thread_count> <row1> <col1> <row2> <col2>\n", argv[0]);
        return 1;
    }

    // Seed for the random number generator
    srand(time(NULL)); 

    // initializing the values for the thread count and dimensions of the the matrices
    thread_count = atoi(argv[1]);
    row1 = atoi(argv[2]);
    col1 = atoi(argv[3]);
    row2 = atoi(argv[4]);
    col2 = atoi(argv[5]);

    if (col1 != row2)
    {
        printf("Dimension Error!!!!!!!\n");
        printf("Cannot multiply these two matrices\n");
        return 1;
    }

    // Allocating memory for the matrices
    matrixA = malloc(row1 * col1 * sizeof(double));
    matrixB = malloc(row2 * col2 * sizeof(double));
    matrixC = malloc(row1 * col2 * sizeof(double));



    return 0;
}